/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall NNA_LineFunctionCal(int *a1);
int __fastcall NNA_TempVirFind(int a1, int a2);
int __fastcall NNA_TempNtcFind(unsigned int a1);
int (__fastcall **__fastcall NNA_NtcTempGet(int a1, int a2))(_DWORD, _DWORD);
int __fastcall NNA_VirBlackBodyTempMark(int a1, int a2, int a3);
int __fastcall NNA_VirBlackBodyTempCal(int a1, int a2);
int __fastcall NNA_BlackBodyTempGet(int a1, int a2, int a3, int a4);
signed int __fastcall NNA_HumanBodyTempGet(int a1);
// int __fastcall _aeabi_d2f(_DWORD); weak
// int __fastcall _aeabi_dadd(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall _aeabi_dcmpge(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall _aeabi_dcmpgt(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall _aeabi_dcmple(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall _aeabi_ddiv(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall _aeabi_dmul(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall _aeabi_dsub(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall _aeabi_f2d(_DWORD); weak
// int __fastcall _aeabi_f2iz(_DWORD); weak
// int __fastcall _aeabi_f2uiz(_DWORD); weak
// int __fastcall _aeabi_fadd(_DWORD, _DWORD); weak
// int __fastcall _aeabi_fcmpge(_DWORD, _DWORD); weak
// int __fastcall _aeabi_fcmpgt(_DWORD, _DWORD); weak
// int __fastcall _aeabi_fcmplt(_DWORD); weak
// int __fastcall _aeabi_fdiv(_DWORD, _DWORD); weak
// int __fastcall _aeabi_fsub(_DWORD, _DWORD); weak
// int __fastcall _aeabi_i2f(_DWORD); weak
// int __fastcall _aeabi_memclr4(_DWORD, _DWORD); weak
// int __fastcall _aeabi_ui2d(_DWORD); weak
// int __fastcall _aeabi_ui2f(_DWORD); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_56; // weak
// extern int (__fastcall *_aeabi_fmul[14896])(_DWORD, _DWORD); idb


//----- (00000000) --------------------------------------------------------
int __fastcall NNA_LineFunctionCal(int *a1)
{
  int *v1; // r4
  int v2; // r6
  int v3; // r5
  int v4; // r7
  int v5; // r0
  int v6; // r5
  int v7; // r0
  int v8; // r6
  int v9; // r0
  int result; // r0
  int v11; // r0

  v1 = a1;
  v2 = a1[2];
  v3 = _aeabi_fsub(a1[3], v2);
  v4 = *v1;
  v5 = _aeabi_fsub(v1[1], *v1);
  v6 = _aeabi_fdiv(v3, v5);
  v1[4] = v6;
  v7 = _aeabi_fmul[0](v4, v6);
  v8 = _aeabi_fsub(v2, v7);
  v1[5] = v8;
  if ( *((_BYTE *)v1 + 32) == 1 )
  {
    v9 = _aeabi_fmul[0](v6, v1[6]);
    result = _aeabi_fadd(v8, v9);
    v1[7] = result;
  }
  else
  {
    v11 = _aeabi_fsub(v1[7], v8);
    result = _aeabi_fdiv(v11, v6);
    v1[6] = result;
  }
  return result;
}
// 770: invalid function type has been ignored
// 75C: using guessed type int __fastcall _aeabi_fadd(_DWORD, _DWORD);
// 76C: using guessed type int __fastcall _aeabi_fdiv(_DWORD, _DWORD);
// 774: using guessed type int __fastcall _aeabi_fsub(_DWORD, _DWORD);

//----- (0000006C) --------------------------------------------------------
int __fastcall NNA_TempVirFind(int a1, int a2)
{
  int v2; // r7
  int v3; // r5
  _DWORD *v4; // r6
  unsigned int v5; // r5
  int v6; // r7
  int v7; // r5
  int v8; // r0
  int v9; // r0
  int v11; // [sp+8h] [bp-68h]
  int v12; // [sp+Ch] [bp-64h]
  int v13; // [sp+10h] [bp-60h]
  int v14; // [sp+18h] [bp-58h]
  int v15; // [sp+34h] [bp-3Ch]
  int v16; // [sp+38h] [bp-38h]
  int v17; // [sp+3Ch] [bp-34h]
  int v18; // [sp+40h] [bp-30h]
  int v19; // [sp+44h] [bp-2Ch]
  int v20; // [sp+50h] [bp-20h]
  int v21; // [sp+54h] [bp-1Ch]
  char v22; // [sp+58h] [bp-18h]

  v2 = a2;
  v15 = a1;
  _aeabi_memclr4(&v16, 36);
  MEMORY[0x940B341C] |= 0x8000000u;
  MEMORY[0x7C06830] = -1743924740;
  MEMORY[0x7C06834] = &_aeabi_f2uiz + 14890;
  MEMORY[0x7C06838] = 541541893;
  MEMORY[0x7C0683C] = -1878720384;
  MEMORY[0x7C06820] = (unsigned int)MEMORY[0x49404370] >> 9;
  MEMORY[0x7C06824] = ~((unsigned int)MEMORY[0x4940436C] >> 9);
  MEMORY[0x7C06828] = (unsigned int)MEMORY[0x4940436A] >> 9;
  MEMORY[0x7C0682C] = ~((unsigned int)MEMORY[0x49404368] >> 9);
  MEMORY[0x7C06810] &= 0xFFFFFFFD;
  MEMORY[0x7C06810] |= 1u;
  while ( MEMORY[0x7C06810] << 31 )
    ;
  v3 = _aeabi_f2uiz(v15);
  v4 = (_DWORD *)(284 * v3 - 1333676560);
  v13 = _aeabi_ui2f(v3);
  v12 = _aeabi_ui2f(v3 + 1);
  v14 = _aeabi_i2f(v2);
  v5 = 0;
  while ( 1 )
  {
    v16 = v13;
    v17 = v12;
    v18 = _aeabi_i2f(*v4);
    v19 = _aeabi_i2f(v4[71]);
    v20 = v15;
    v22 = 1;
    NNA_LineFunctionCal(&v16);
    v6 = v21;
    if ( !_aeabi_fcmplt(v21) )
      break;
    ++v4;
    ++v5;
    v11 = v6;
    if ( v5 >= 0x47 )
    {
      v7 = 1177643200;
      goto LABEL_8;
    }
  }
  v18 = _aeabi_i2f(v5 - 1);
  v19 = _aeabi_ui2f((unsigned __int8)v5);
  v16 = v11;
  v17 = v6;
  v20 = v14;
  v22 = 1;
  NNA_LineFunctionCal(&v16);
  v7 = _aeabi_fmul[0](v21, 1753630212);
LABEL_8:
  MEMORY[0x7C06810] &= 0xFFFFFFFD;
  MEMORY[0x7C06810] |= 1u;
  v8 = _aeabi_ui2f(MEMORY[0x7C06828] << 20 >> 28);
  v9 = _aeabi_fdiv(v7, v8);
  while ( MEMORY[0x7C06810] << 31 )
    ;
  MEMORY[0x940B341C] &= 0xF7FFFFFF;
  return _aeabi_fadd(v9, &_aeabi_fsub + 14883);
}
// 770: invalid function type has been ignored
// 758: using guessed type int __fastcall _aeabi_f2uiz(_DWORD);
// 75C: using guessed type int __fastcall _aeabi_fadd(_DWORD, _DWORD);
// 768: using guessed type int __fastcall _aeabi_fcmplt(_DWORD);
// 76C: using guessed type int __fastcall _aeabi_fdiv(_DWORD, _DWORD);
// 774: using guessed type int __fastcall _aeabi_fsub(_DWORD, _DWORD);
// 778: using guessed type int __fastcall _aeabi_i2f(_DWORD);
// 77C: using guessed type int __fastcall _aeabi_memclr4(_DWORD, _DWORD);
// 784: using guessed type int __fastcall _aeabi_ui2f(_DWORD);

//----- (00000210) --------------------------------------------------------
int __fastcall NNA_TempNtcFind(unsigned int a1)
{
  unsigned int v1; // r4
  int v3; // [sp+0h] [bp-38h]
  int v4; // [sp+4h] [bp-34h]
  int v5; // [sp+8h] [bp-30h]
  int v6; // [sp+Ch] [bp-2Ch]
  int v7; // [sp+18h] [bp-20h]
  int v8; // [sp+1Ch] [bp-1Ch]
  char v9; // [sp+20h] [bp-18h]
  int v10; // [sp+24h] [bp-14h]

  v1 = a1;
  _aeabi_memclr4(&v3, 36);
  LOBYTE(v10) = 0;
  do
  {
    if ( *(_DWORD *)(4 * (unsigned __int8)v10 + 0xA498901) >= v1
      && *(_DWORD *)(4 * (unsigned __int8)v10 + 0xA498905) <= v1 )
    {
      break;
    }
    LOBYTE(v10) = v10 + 1;
  }
  while ( (unsigned __int8)v10 < 0x24u );
  v9 = 0;
  v8 = _aeabi_ui2f(v1);
  v3 = _aeabi_i2f((unsigned __int8)v10 + 1);
  v4 = _aeabi_ui2f((unsigned __int8)v10);
  v5 = _aeabi_ui2f(*(_DWORD *)(4 * (unsigned __int8)v10 + 0xA498905));
  v6 = _aeabi_ui2f(*(_DWORD *)(4 * (unsigned __int8)v10 + 0xA498901));
  NNA_LineFunctionCal(&v3);
  return v7;
}
// 778: using guessed type int __fastcall _aeabi_i2f(_DWORD);
// 77C: using guessed type int __fastcall _aeabi_memclr4(_DWORD, _DWORD);
// 784: using guessed type int __fastcall _aeabi_ui2f(_DWORD);

///< NTCH, NTCL
//----- (000002A4) --------------------------------------------------------
int (__fastcall **__fastcall NNA_NtcTempGet(int a1, int a2))(_DWORD, _DWORD)
{
  int v2; // r5
  int v3; // r4
  int v4; // r6
  int v5; // r0
  int v6; // r5
  int v7; // r0
  int v8; // r0
  unsigned int v9; // r0
  int v10; // r0
  int v11; // r4
  int (__fastcall **v12)(_DWORD, _DWORD); // r5

  v2 = a2;
  v3 = MEMORY[0x6886460C];
  v4 = _aeabi_ui2f(a1 * MEMORY[0x6886460C]);
  v5 = _aeabi_ui2f(v2);
  v6 = _aeabi_fdiv(v4, v5);
  v7 = _aeabi_ui2f(v3);
  v8 = _aeabi_fsub(v6, v7);
  v9 = _aeabi_f2uiz(v8);
  v10 = NNA_TempNtcFind(v9);
  v11 = _aeabi_fadd(v10, 1177643200);
  v12 = &_aeabi_fsub + 14883;
  if ( !_aeabi_fcmpge(v11, &_aeabi_fsub + 14883) )
  {
    v12 = (int (__fastcall **)(_DWORD, _DWORD))v11;
    if ( !_aeabi_fcmpgt(v11, 1177643200) )
      v12 = (int (__fastcall **)(_DWORD, _DWORD))1177643200;
  }
  return v12;
}
// 758: using guessed type int __fastcall _aeabi_f2uiz(_DWORD);
// 75C: using guessed type int __fastcall _aeabi_fadd(_DWORD, _DWORD);
// 760: using guessed type int __fastcall _aeabi_fcmpge(_DWORD, _DWORD);
// 764: using guessed type int __fastcall _aeabi_fcmpgt(_DWORD, _DWORD);
// 76C: using guessed type int __fastcall _aeabi_fdiv(_DWORD, _DWORD);
// 774: using guessed type int __fastcall _aeabi_fsub(_DWORD, _DWORD);
// 784: using guessed type int __fastcall _aeabi_ui2f(_DWORD);

///< 
//----- (00000310) --------------------------------------------------------
int __fastcall NNA_VirBlackBodyTempMark(int a1, int a2, int a3)
{
  int v3; // r5
  int v4; // r4
  int v5; // r7
  int v6; // r1
  int v8; // [sp+0h] [bp-38h]
  int v9; // [sp+4h] [bp-34h]
  int v10; // [sp+8h] [bp-30h]
  int (__fastcall *v11)(_DWORD, _DWORD); // [sp+Ch] [bp-2Ch]
  int v12; // [sp+10h] [bp-28h]
  int v13; // [sp+18h] [bp-20h]
  int v14; // [sp+1Ch] [bp-1Ch]
  char v15; // [sp+20h] [bp-18h]

  v3 = a3;
  v4 = a2;
  v5 = a1;
  _aeabi_memclr4(&v12, 20);
  v15 = 1;
  v13 = v5;
  v6 = (int)_aeabi_fmul[14894];
  v11 = _aeabi_fmul[14895];
  v10 = v6;
  v9 = v3;
  v8 = v4;
  NNA_LineFunctionCal(&v8);
  return v14;
}
// 77C: using guessed type int __fastcall _aeabi_memclr4(_DWORD, _DWORD);

//----- (0000034C) --------------------------------------------------------
int __fastcall NNA_VirBlackBodyTempCal(int a1, int a2)
{
  int v2; // r5
  int v3; // r6
  int v4; // r7
  int v5; // r0
  _DWORD *v6; // r4
  int v7; // r0
  int v9; // [sp+0h] [bp-18h]

  v2 = a2;
  v9 = a1;
  v3 = MEMORY[0x9201681C];
  v4 = _aeabi_fcmplt(MEMORY[0x9201681C]);
  v5 = _aeabi_fsub(v3, v2);
  if ( v4 )
    v6 = (_DWORD *)-1845401576;
  else
    v6 = (_DWORD *)-1845401580;
  v7 = _aeabi_fmul[0](v5, *v6);
  return _aeabi_fadd(v7, v9);
}
// 770: invalid function type has been ignored
// 75C: using guessed type int __fastcall _aeabi_fadd(_DWORD, _DWORD);
// 768: using guessed type int __fastcall _aeabi_fcmplt(_DWORD);
// 774: using guessed type int __fastcall _aeabi_fsub(_DWORD, _DWORD);

///< NTC, VIR, Bias, isCal
//----- (00000388) --------------------------------------------------------
int __fastcall NNA_BlackBodyTempGet(int a1, int a2, int a3, int a4)
{
  int v4; // r7
  int v5; // ST00_4
  int v6; // r4
  int v7; // r7
  int v8; // r0
  int v9; // r5
  int v10; // r0
  int v11; // r7
  int v12; // r4
  int v13; // r0
  int v14; // r0
  int v15; // r0
  int v16; // r0
  int v17; // r0
  int v18; // r4
  int v19; // r0
  int v20; // r4
  void *v21; // r6
  int v22; // r6
  int v23; // r0
  int v24; // r1
  int v25; // r0
  int v26; // r4
  int v27; // r0
  int v28; // r1
  int v29; // r0
  int v30; // r2
  int v31; // r0
  int v32; // r1
  int v33; // r0
  int v35; // [sp+4h] [bp-1Ch]
  int v36; // [sp+8h] [bp-18h]

  v35 = a4;
  v4 = a3;
  v5 = a2;
  v36 = a1;
  v6 = _aeabi_ui2f(MEMORY[0x495806DA]);
  v7 = _aeabi_ui2f(v4);
  v8 = _aeabi_ui2f(MEMORY[0x495806DE]);
  v9 = v8;
  v10 = _aeabi_fdiv(v7, v8);
  v11 = _aeabi_fmul[0](v10, v6);
  v12 = _aeabi_fdiv(v6, v9);
  v13 = _aeabi_ui2f(v5);
  v14 = _aeabi_fmul[0](v12, v13);
  v15 = _aeabi_fsub(v14, v11);
  v16 = _aeabi_fmul[0](MEMORY[0x495806F6], v15);
  v17 = _aeabi_fdiv(v16, MEMORY[0x495806F2]);
  v18 = _aeabi_f2iz(v17);
  v19 = _aeabi_fadd(v36, -1845401592);
  // Table Search
  v20 = NNA_TempVirFind(v19, v18);
  v21 = (void *)1611154192;
  if ( !_aeabi_fcmpge(v20, 1611154192) )
  {
    v21 = (void *)v20;
    if ( !_aeabi_fcmpgt(v20, &loc_56) )
      v21 = &loc_56;
  }
  v22 = _aeabi_fdiv(v21, 1213686288);
  if ( v35 == 1 )
  {
    // Cal
    v23 = _aeabi_ui2d((unsigned __int16)*MEMORY[0x4958070A]);
    v25 = _aeabi_ddiv(v23, v24, 0, 1213686352);
    v26 = _aeabi_d2f(v25);
    v27 = _aeabi_ui2d((unsigned __int16)*MEMORY[0x4958070E]);
    v29 = _aeabi_ddiv(v27, v28, 0, 1213686352);
    v30 = _aeabi_d2f(v29);
    v31 = v22;
    v32 = v26;
  }
  else
  {
    v32 = MEMORY[0x495806FA]; //NTCL
    v30 = MEMORY[0x495806FE]; //NTCH
    v31 = v22;
  }
  v33 = NNA_VirBlackBodyTempMark(v31, v32, v30); //VIR, NTCL, NTCH
  return NNA_VirBlackBodyTempCal(v33, v36); //Vbody,  NTC
}
// 770: invalid function type has been ignored
// 730: using guessed type int __fastcall _aeabi_d2f(_DWORD);
// 744: using guessed type int __fastcall _aeabi_ddiv(_DWORD, _DWORD, _DWORD, _DWORD);
// 754: using guessed type int __fastcall _aeabi_f2iz(_DWORD);
// 75C: using guessed type int __fastcall _aeabi_fadd(_DWORD, _DWORD);
// 760: using guessed type int __fastcall _aeabi_fcmpge(_DWORD, _DWORD);
// 764: using guessed type int __fastcall _aeabi_fcmpgt(_DWORD, _DWORD);
// 76C: using guessed type int __fastcall _aeabi_fdiv(_DWORD, _DWORD);
// 774: using guessed type int __fastcall _aeabi_fsub(_DWORD, _DWORD);
// 780: using guessed type int __fastcall _aeabi_ui2d(_DWORD);
// 784: using guessed type int __fastcall _aeabi_ui2f(_DWORD);

//----- (00000498) --------------------------------------------------------
signed int __fastcall NNA_HumanBodyTempGet(int a1)
{
  int v1; // r4
  int v2; // r5
  int v3; // r7
  int v4; // r0
  signed int v5; // r1
  signed int v6; // r5
  int v7; // r0
  int v8; // r1
  int v9; // r0
  int v10; // r1
  int v11; // r0
  int v12; // r1
  int v13; // r0
  int v14; // r1
  int v15; // r4
  int v16; // r1
  int v17; // r5
  int v18; // r0
  int v19; // r1
  int v20; // r2
  signed int v21; // r1
  signed int v22; // r3
  int v23; // r0
  int v24; // r1
  int v25; // r0
  int v26; // r4
  int v27; // r1
  int v28; // r5
  int v29; // r0
  int v30; // r1
  int v31; // r0
  int v32; // r1
  int v33; // r0
  int v34; // r1
  int v35; // r0
  int v36; // r1
  int v37; // r0
  signed int v38; // r5

  v1 = a1;
  MEMORY[0xF0004620] |= 0x8000000u;
  MEMORY[0x2301FB9F] = 1230505690;
  MEMORY[0x2301FBA3] = -1845401592;
  MEMORY[0x2301FBA7] = 1611154192;
  MEMORY[0x2301FBAB] = &loc_56;
  MEMORY[0x2301FB8F] = (unsigned int)MEMORY[0x48576216] >> 9;
  MEMORY[0x2301FB93] = (unsigned int)MEMORY[0x48576214] >> 9;
  MEMORY[0x2301FB97] = (unsigned int)MEMORY[0x48576212] >> 9;
  MEMORY[0x2301FB9B] = (unsigned int)MEMORY[0x48576210] >> 9;
  MEMORY[0x2301FB7F] &= 0xFFFFFFFD;
  MEMORY[0x2301FB7F] |= 1u;
  while ( MEMORY[0x2301FB7F] << 31 )
    ;
  v2 = (MEMORY[0x2301FB93] >> 8) & 0xE;
  v3 = _aeabi_f2d(a1);
  v4 = 10 * v2;
  v6 = v5;
  v7 = _aeabi_ui2d(v4);
  v9 = _aeabi_dadd(v7, v8, 0, 1213686352);
  if ( !_aeabi_dcmpge(v9, v10, v3, v6) )
  {
    if ( _aeabi_fcmplt(v1) || _aeabi_dcmpgt(v3, v6, 1213686480, 172591361) )
    {
      if ( !_aeabi_fcmpge(v1, 172001280) && !_aeabi_dcmple(v3, v6, 1213686480, 172591361) )
      {
        v25 = _aeabi_fadd(v1, -1811205092);
LABEL_16:
        v1 = v25;
        goto LABEL_17;
      }
      if ( _aeabi_fcmplt(v1) || _aeabi_dcmpgt(v3, v6, 1641038784, 553805840) )
      {
        v31 = _aeabi_ui2d(10 * (MEMORY[0x2301FB93] << 20 >> 28));
        v33 = _aeabi_dsub(0, 1176539146, v31, v32);
        v35 = _aeabi_dmul(v33, v34, -1878577144, 806110752);
        v23 = _aeabi_dadd(v35, v36, 1176539144, -1878446056);
        v20 = v3;
        v22 = v6;
      }
      else
      {
        v26 = _aeabi_dmul(v3, v6, 1133023488, 1745903632);
        v28 = v27;
        v29 = _aeabi_ui2d(MEMORY[0x2301FB8F] << 24 >> 28);
        v23 = _aeabi_dadd(v26, v28, v29, v30);
        v20 = 1125683980;
        v22 = 488661008;
      }
    }
    else
    {
      v11 = _aeabi_ui2d(MEMORY[0x2301FB97] << 24 >> 28);
      v13 = _aeabi_dadd(v11, v12, -2004786927, 1137248841);
      v15 = _aeabi_dmul(v13, v14, v3, v6);
      v17 = v16;
      v18 = _aeabi_ui2d(10 * ((MEMORY[0x2301FB8F] >> 4) & 0xC));
      v20 = _aeabi_dsub(-2008981167, 1636895305, v18, v19);
      v22 = v21;
      v23 = v15;
      v24 = v17;
    }
    v37 = _aeabi_dadd(v23, v24, v20, v22);
    v25 = _aeabi_d2f(v37);
    goto LABEL_16;
  }
LABEL_17:
  MEMORY[0x2301FB7F] |= 1u;
  while ( MEMORY[0x2301FB7F] << 31 )
    ;
  MEMORY[0xF0004620] &= 0xF7FFFFFF;
  v38 = 130050064;
  if ( !_aeabi_fcmpge(v1, 130050064) )
  {
    v38 = v1;
    if ( !_aeabi_fcmpgt(v1, -1743924740) )
      v38 = -1743924740;
  }
  return v38;
}
// 730: using guessed type int __fastcall _aeabi_d2f(_DWORD);
// 734: using guessed type int __fastcall _aeabi_dadd(_DWORD, _DWORD, _DWORD, _DWORD);
// 738: using guessed type int __fastcall _aeabi_dcmpge(_DWORD, _DWORD, _DWORD, _DWORD);
// 73C: using guessed type int __fastcall _aeabi_dcmpgt(_DWORD, _DWORD, _DWORD, _DWORD);
// 740: using guessed type int __fastcall _aeabi_dcmple(_DWORD, _DWORD, _DWORD, _DWORD);
// 748: using guessed type int __fastcall _aeabi_dmul(_DWORD, _DWORD, _DWORD, _DWORD);
// 74C: using guessed type int __fastcall _aeabi_dsub(_DWORD, _DWORD, _DWORD, _DWORD);
// 750: using guessed type int __fastcall _aeabi_f2d(_DWORD);
// 75C: using guessed type int __fastcall _aeabi_fadd(_DWORD, _DWORD);
// 760: using guessed type int __fastcall _aeabi_fcmpge(_DWORD, _DWORD);
// 764: using guessed type int __fastcall _aeabi_fcmpgt(_DWORD, _DWORD);
// 768: using guessed type int __fastcall _aeabi_fcmplt(_DWORD);
// 780: using guessed type int __fastcall _aeabi_ui2d(_DWORD);

// ALL OK, 8 function(s) have been successfully decompiled
